# -*- coding: utf-8 -*-
"""miniprojectusingML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OT_bnR49YNLhnH9Rgcd7Lnep6xfWdvUh
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
df = pd.read_csv("/content/drive/MyDrive/ML Project/genres/features_3_sec.csv")

df.head()

"""#Checking for duplicates"""

boolean = df.duplicated().sum()
print(boolean)

df.duplicated().sum()
df.drop_duplicates
df.isnull().sum()

"""#Dropping duplicates"""

df.drop_duplicates

"""#Checking for null values"""

print(df.isnull().sum())

df['label'].nunique()

df['label'].unique()

"""#Converting categorical label values to numerical values"""

from sklearn.preprocessing import LabelEncoder
labelencoder= LabelEncoder()
df['label'] = labelencoder.fit_transform(df['label'])
print(df['label'])

from sklearn.preprocessing import LabelEncoder
labelencoder= LabelEncoder()
df['label'] = labelencoder.fit_transform(df['label'])

print(df['label'])

df.drop(['filename'],axis=1,inplace=True)
df.head()

"""*italicized text*#Doing PCA"""

from sklearn.decomposition import PCA
from sklearn.decomposition import PCA
pca = PCA(whiten=True)
pca.fit(df)
variance = pd.DataFrame(pca.explained_variance_ratio_)
np.cumsum(pca.explained_variance_ratio_)



from sklearn.decomposition import PCA
from sklearn.decomposition import PCA
pca = PCA(whiten=True)
pca.fit(df)
variance = pd.DataFrame(pca.explained_variance_ratio_)
np.cumsum(pca.explained_variance_ratio_)
pca = PCA(n_components=25,whiten=True)
pca = pca.fit(df)
dataPCA = pd.DataFrame(pca.transform(df))

X= dataPCA

print(X)

"""#Split data for training and testing"""

y = df.iloc[:,-1]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

"""#Decision tree"""

from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier().fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(accuracy_score(y_pred, y_test)*100)



"""#Random Forest"""

from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

from sklearn.ensemble import RandomForestClassifier

rf= RandomForestClassifier(n_estimators=100,random_state=0)
rf.fit(X_train,y_train)

y_pred= rf.predict(X_test)
print("Accuracy Score RandomForest: ",accuracy_score(y_test,y_pred))

"""#KNN"""

from sklearn.neighbors import KNeighborsClassifier
classifier= KNeighborsClassifier(n_neighbors=5)  #it's changing based on n_neighbors value
classifier.fit(X_train, y_train)

y_pred= classifier.predict(X_test)

print("Accuracy score: ", accuracy_score(y_pred, y_test)*100)

"""#Naive bayes"""

from sklearn.naive_bayes import GaussianNB
nb_model = GaussianNB()
nb_model = nb_model.fit(X_train,y_train)
y_pred = nb_model.predict(X_test)
print(accuracy_score(y_pred, y_test)*100)

"""#XG Booster"""

from xgboost import XGBClassifier

from xgboost import XGBClassifier
model = XGBClassifier(n_estimators=1000)
model.fit(X_train,y_train,eval_metric='merror')
y_pred_train = model.predict(X_train)
y_pred_test = model.predict(X_test)
target_names = sorted(set(y))

print(f'Training accuracy: {accuracy_score(y_train,y_pred_train)}')
#print(f'Training:\n {classification_report(y_train, y_pred_train, labels=target_names)}')
print(f'Testing accuracy: {accuracy_score(y_test,y_pred_test)}')
#print(f'Testing:\n {classification_report(y_test, y_pred_test, labels=target_names)}')

y_pred_train = model.predict(X_train)
y_pred_test = model.predict(X_test)
target_names = sorted(set(y))

print(f'Training accuracy: {accuracy_score(y_train,y_pred_train)}')
#print(f'Training:\n {classification_report(y_train, y_pred_train, labels=target_names)}')
print(f'Testing accuracy: {accuracy_score(y_test,y_pred_test)}')
#print(f'Testing:\n {classification_report(y_test, y_pred_test, labels=target_names)}')

"""#Logistic regression"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Accuracy Score: ",accuracy_score(y_pred,y_test))



from sklearn.metrics import r2_score, mean_squared_error
from sklearn.metrics import confusion_matrix
from sklearn import metrics

unique_labels, counts = np.unique(y_test, return_counts=True)

# Print the counts for each unique label
for label, count in zip(unique_labels, counts):
    print(f"Label {label}: {count} occurrences")

y_pred= LogReg.predict(X_test)
print("Accuracy Score: ",metrics.accuracy_score(y_pred,y_test))
print(metrics.confusion_matrix(y_test,y_pred))

"""#Support vector machine"""

from sklearn.svm import SVC
svm_model = SVC()
svm_model = svm_model.fit(X_train,y_train)
y_pred = svm_model.predict(X_test)
print(accuracy_score(y_pred, y_test)*100)

"""#CNN"""

df = pd.read_csv("/content/drive/MyDrive/ML Project/genres/features_3_sec.csv")
df.head()

class_encod=df.iloc[:,-1]
converter=LabelEncoder()
y=converter.fit_transform(class_encod)
y

#Drop the column filename as it is no longer required for training
df=df.drop(labels="filename",axis=1)

#scaling
from sklearn.preprocessing import StandardScaler
fit=StandardScaler()
X=fit.fit_transform(np.array(df.iloc[:,:-1],dtype=float))

# splitting 70% data into training set and the remaining 30% to test set
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

def train_model(model,epochs,optimizer):
    batch_size=256
    model.compile(optimizer=optimizer,loss='sparse_categorical_crossentropy',metrics='accuracy')
    return model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=epochs,batch_size=batch_size)

def Validation_plot(history):
    print("Validation Accuracy",max(history.history["val_accuracy"]))

model=tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(X.shape[1],)),
    tf.keras.layers.Dropout(0.2),

    tf.keras.layers.Dense(512,activation='relu'),
    keras.layers.Dropout(0.2),

    tf.keras.layers.Dense(256,activation='relu'),
    tf.keras.layers.Dropout(0.2),

    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),

    tf.keras.layers.Dense(64,activation='relu'),
    tf.keras.layers.Dropout(0.2),

    tf.keras.layers.Dense(32,activation='relu'),
    tf.keras.layers.Dropout(0.2),

    tf.keras.layers.Dense(10,activation='softmax'),
])

optimizer = tf.keras.optimizers.Adam(learning_rate=0.000146)
model.compile(optimizer=optimizer,
             loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])
model.summary()
model_history=train_model(model=model,epochs=600,optimizer='adam')

test_loss,test_acc=model.evaluate(X_test,y_test,batch_size=256)
print("The test loss is ",test_loss)
print("The best accuracy is: ",test_acc*100)

# The plot dipicts how training and testing data performed
Validation_plot(model_history)